#!/bin/bash

## HOWTO
# example:
# >>wol r001
# will wakeonlan all host, which hostname starts with r001
# r001pc01, r001pc02, ...

## check, if dhcp/dhcpd.conf is available

DHCP_REPOSITORY="https://github.com/edvapp/dhcp"
DHCPD_DIRECTORY="dhcp"
DHCPD_FILE="$DHCPD_DIRECTORY/dhcpd.conf"

if [ ! -d $DHCPD_DIRECTORY ];
then
	git clone $DHCP_REPOSITORY
else
	cd $DHCPD_DIRECTORY
	git pull 
	cd ..
fi

## get pattern from console
PATTERN=$1

MACLIST=$(grep -E $PATTERN $DHCPD_FILE | grep -o -E [a-fA-F0-9]{2}:[a-fA-F0-9]{2}:[a-fA-F0-9]{2}:[a-fA-F0-9]{2}:[a-fA-F0-9]{2}:[a-fA-F0-9]{2})

for MAC in $MACLIST;
do
	grep -E $MAC $DHCPD_FILE | awk '{ print "wakonlan host: " $2 " with MAC: " $6 }'
	wakeonlan $MAC;
	echo ""
done
